spring:
  kafka:
    template:
      observation-enabled: true # set kafka producer headers

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4317}
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_HTTP_BASE_URL:http://localhost:4318}/v1/metrics
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: 1.0 # report 100% of traces
    export:
      enabled: true
