spring:
  kafka:
    template:
      observation-enabled: true # set kafka producer headers

management:
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: 1.0 # report 100% of traces
    export:
      enabled: true
