package com.icthh.xm.ms.entity.lep;

import com.icthh.lep.api.ContextScopes;
import com.icthh.lep.api.ContextsHolder;
import com.icthh.lep.api.ScopedContext;
import com.icthh.xm.ms.entity.config.tenant.TenantInfo;
import lombok.experimental.UtilityClass;

/**
 * The {@link LepContextUtils} class.
 */
@UtilityClass
@SuppressWarnings("squid:S1118") // private constructor generated by lombok
final class LepContextUtils {

    public static String getTenantName(ContextsHolder lepContextsHolder) {
        ScopedContext scopedContext = getThreadContext(lepContextsHolder);
        TenantInfo tenantInfo = scopedContext.getValue(XmLepConstants.CONTEXT_KEY_TENANT,
                                                       TenantInfo.class);
        if (tenantInfo == null) {
            throw new IllegalStateException(
                "LEP manager thread context doesn't have value for var: "
                    + XmLepConstants.CONTEXT_KEY_TENANT);
        }
        return tenantInfo.getTenant();
    }

    private static ScopedContext getThreadContext(ContextsHolder lepContextsHolder) {
        ScopedContext scopedContext = lepContextsHolder.getContext(ContextScopes.THREAD);
        if (scopedContext == null) {
            throw new IllegalStateException("LEP manager thread context doesn't initialized. "
                                                + "Be sure that LepManager.beginThreadContext is called");
        }
        return scopedContext;
    }

}
